version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    ports:
      - "8084:8080"
    depends_on:
      - postgres